project:
  type: website

website:
  title: Kane Carlock
  site-url: https://www.kanecarlock.netlify.app
  twitter-card:
    image: "https://github.com/kanecarlock/Kanes-Website/blob/e2e47c8f8aaa2b0be9cfc6df2d18fbdad048d6a5/twitterpic.jpg"
    site: "https://kanecarlock.netlify.app"
    creator: "@kanecarlock"
  navbar:
    background: brown
    search: true
    right:
      - icon: github
        text: Github
        href: https://github.com/kanecarlock
      - icon: twitter
        text: Twitter
        href: https://twitter.com/kanecarlock
      - icon: orcid_id
        text: ORCID
        href: https://orcid.org/0000-0003-1348-1635
      - icon: Google Scholar
        text: Google Scholar
        href: https://scholar.google.com/citations?user=YwuOtN0AAAAJ&hl=en&oi=ao
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "About Me"
        contents:
        - text: "Home"
          file: index.qmd
        - text: "My CV"
          file: My CV.qmd
      - section: "Resources"
        contents:
        - text: "RStats"
          file: Learning R.qmd
        - text: "Statistics"
          file: Learning Stats.qmd
        - text: "Implementation Science"
          file: Learning Implementation Science.qmd
        - text: "Academia"
          file: Academia.qmd
        - text: "Research"
          file: Research.qmd
        - text: "Computer Science"
          file: Computer.Science.qmd
  google-analytics: G-Y0NH6JS2X2
format:
  html:
    theme: superhero
    css: styles.css
    editor: visual
