project:
  type: website

website:
  title: Kane Carlock
  site-url: https://www.kanecarlock.netlify.app
  twitter-card: true
  creator: "@kanecarlock"
  navbar:
    background: black
    search: true
    right:
      - icon: github
        href: https://github.com/kanecarlock
      - icon: twitter
        href: https://twitter.com/kanecarlock
    left: 
      - text: "Home"
        file: index.qmd
format:
  html:
    theme: superhero
    css: styles.css
    editor: visual
