project:
  type: website

website:
  title: Kane Carlock
  site-url: https://www.kanecarlock.netlify.app
  twitter-card:
    image: "https://github.com/kanecarlock/Kanes-Website/blob/e2e47c8f8aaa2b0be9cfc6df2d18fbdad048d6a5/twitterpic.jpg"
    site: "https://kanecarlock.netlify.app"
    creator: "@kanecarlock"
  navbar:
    background: brown
    search: true
    right:
      - icon: github
        text: github
        href: https://github.com/kanecarlock
      - icon: twitter
        text: twitter
        href: https://twitter.com/kanecarlock
      - icon: orcid_id
        text: ORCID
        href: https://orcid.org/0000-0003-1348-1635
      - icon: Google Scholar
        text: Google Scholar
        href: https://scholar.google.com/citations?user=YwuOtN0AAAAJ&hl=en&oi=ao
    left: 
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Resources"
        file: resources.qmd
  google-analytics: G-Y0NH6JS2X2
format:
  html:
    theme: superhero
    css: styles.css
    editor: visual
