project:
  type: website

website:
  title: "Kanes-Website"
  twitter-card: true
  creator: "@kanecarlock"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kanecarlock
      - icon: twitter
        href: https://twitter.com/kanecarlock
format:
  html:
    theme: superhero
    css: styles.css
    editor: visual
