project:
  type: website

website:
  title: Kane Carlock
  site-url: https://www.kanecarlock.netlify.app
  twitter-card: true
  creator: "@kanecarlock"
  navbar:
    background: brown
    search: true
    right:
      - icon: github
        href: https://github.com/kanecarlock
      - icon: twitter
        href: https://twitter.com/kanecarlock
      - icon: orcidid
        href: https://orcid.org/0000-0003-1348-1635
    left: 
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Resources"
        file: resources.qmd
format:
  html:
    theme: superhero
    css: styles.css
    editor: visual
